### ISSUE TITLE
Using Preheat

### ISSUE THREAD

**Issue by zackshapiro** [kean/Preheat#5]
Hi Alexander,

I'm interested in using Preheat for my project to load very deep view structures before I need them. I was looking at the code a bit, my hesitation is that Preheat may not be tool I'm looking for. Can you speak to its performance for doing that kind of preloading rather than just purely images?

Thanks!
Zack

**Comment by kean** [comment]
Hi @zackshapiro. You can use Preheat for any kind of prefetching, including the case that you've described. It's a tiny library, just try it in your project and see how it works for you. Please let me know if there are some improvements that you'd like to see.

**Comment by zackshapiro** [comment]
@kean thanks for the quick reply! I'm going to give it a try later today. If I'm pre-loading a view that's very complex, any chance the UI will block?

**Comment by kean** [comment]
@zackshapiro sorry, can't help you with that. It depends on what you're trying to achieve and goes out of scope of Preheat. In general I would recommend to avoid any premature optimizations though.

**Comment by zackshapiro** [comment]
I'm just trying to make sure the next view is built and ready to go for the user where the building of the UI doesn't interfere with the user

**Comment by zackshapiro** [comment]
I'll just give it a go and see what happens :)
