### ISSUE TITLE
Could not cast value of type 'FlexiCollectionViewLayout.FlexiCollectionViewLayout'  to 'UICollectionViewFlowLayout' 

### ISSUE THREAD

**Issue by chepil** [kean/Preheat#7]
Привет. Я не силен в swift, только начинаю его изучать, прошу помочь. 
Я использую кастомный layout (FlexiCollectionViewLayout)

Как следствие, приложение падает при попытке cast типов

Could not cast value of type 'FlexiCollectionViewLayout.FlexiCollectionViewLayout' (0x103ffe070) to 'UICollectionViewFlowLayout' (0x1055a2a48).

Падает вот в этом месте 
extension UICollectionView: Preheated {
    public var orientation: ScrollOrientation {
        **switch (collectionViewLayout as! UICollectionViewFlowLayout).scrollDirection {**
        case .vertical: return .vertical
        case .horizontal: return .horizontal
        }
    }

Падает потому, что я использую FlexiCollectionViewLayout, тогда как Preheared желает получить layout как UICollectionViewFlowLayout

Смысл проблемы понятен, но как исправить, я не понимаю, очень прошу помочь. 

Вот кусок кода загрузки контроллера... 
 

override func viewDidLoad() {
        super.viewDidLoad()

        preheater = Preheater()
        preheatController = Preheat.Controller(view: self.collectionView!)
        preheatController.handler = { [weak self] addedIndexPaths, removedIndexPaths in
            self?.preheat(added: addedIndexPaths, removed: removedIndexPaths)
        }
        
        let layout = FlexiCollectionViewLayout()
        collectionView?.collectionViewLayout = layout

**Comment by kean** [comment]
Привет! Preheat поддерживает только UICollectionViewFlowLayout или его наследниками. Он не умеет работать с кастомными лейаутами.

**Comment by chepil** [comment]
Саша, спасибо, да, я понимаю по коду - 
public var orientation: ScrollOrientation {
        switch (collectionViewLayout as! UICollectionViewFlowLayout).scrollDirection {
        case .vertical: return .vertical
        case .horizontal: return .horizontal
        }
    }
    
Но, можно ли как то это обойти ? Кроме как написать свой собственный класс... Никак нельзя переопределить это с помощью 
extension UICollectionView: Preheated {
    public var orientation: ScrollOrientation {
в моем собственном коде ?
Вопрос не очень умный, не разобрался со свифтом...  

Эта штука, в принципе, наследник - 
@objc open class FlexiCollectionViewLayout: UICollectionViewLayout {
...
@objc public protocol FlexiCollectionViewLayoutDelegate: UICollectionViewDelegateFlowLayout {

**Comment by kean** [comment]
Я изначально не закладывал поддержку кастомных лейаутов для UICollectionView. Не думаю, что это сложно поддержать. Если будет желание расширить Preheat, я готов буду вмержить PR (желательно с обратной совместимостью). Я, к сожалению, с этим сейчас не смогу помочь.

**Comment by chepil** [comment]
Саша, спасибо, я понял. Буду изучать вопрос, не заморачивайся, просто мое незнание. Нужно подумать и разобраться :-) Спасибо!

**Comment by kean** [comment]
Можно просто попробовать сделать `FlexiCollectionViewLayout` наследником `UICollectionViewFlowLayout`, если есть доступ к сорсам. Это проще всего.

**Comment by chepil** [comment]
Понял, спасибо, я уже немножко переписал Preheat под себя. Убрал его из Pod, добавил к себе, переписал. Так оказалось проще. Работает. Отличная библиотека! Спасибо большое!
